version: '3'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "justeats"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user", "-d", "justeats" ]
      interval: 3s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgressql/data
    networks:
      - postgres-network

networks:
  postgres-network:
    name: postgres-network
    driver: bridge