Resources:
  RestaurantLogoBucketS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${opt:stage, self:provider.stage}-justeats-restaurant-logo

  RestaurantLogoBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: RestaurantLogoBucketS3
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource:
              Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: RestaurantLogoBucketS3
                  - '/*'
